substitutions:
  device_suffix: "stairs"
  wifi_ssid: !secret WIFI_SSID
  wifi_password: !secret WIFI_PASSWORD

packages:
  dimled: github://tqlabs-in/dimled-mark-2/esphome/device/base.yaml@main
  # dimled:
  #   url: https://github.com/tqlabs-in/dimled-mark-2/esphome
  #   files: [device/base.yaml]
  #   ref: main
  #   refresh: always
