---
substitutions:
  light_strip_id: led_strip

globals:
  - id: should_increase
    type: bool
    restore_value: no
    initial_value: "true"

light:
  - id: !extend $light_strip_id
    on_state:
      - lambda: |-
          bool is_on = id(led_strip).current_values.is_on();
          if(!is_on) {
            return;
          }

          float b = id(led_strip).current_values.get_brightness();
          if(b <= 0.05f) {
            id(should_increase) = true;
          } else if(b == 1.0f) {
            id(should_increase) = false;
          }

binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      # Hold
      - timing:
          - ON for at least 500ms
        then:
          - lambda: |-
              bool is_on = id(led_strip).current_values.is_on();
              if(!is_on) {
                id(should_increase) = true;
                return;
              }

              float b = id(led_strip).current_values.get_brightness();
              if (b <= 0.05f) {
                id(should_increase) = true;
              } else if (b >= 0.95f) {
                id(should_increase) = false;
              }
          - if:
              condition:
                lambda: "return id(should_increase) == true;"
              then:
                - while:
                    condition:
                      binary_sensor.is_on: boot_button
                    then:
                      - light.dim_relative:
                          id: led_strip
                          relative_brightness: 2%
                          transition_length: 200ms
                      - delay: 100ms
              else:
                - while:
                    condition:
                      binary_sensor.is_on: boot_button
                    then:
                      - light.dim_relative:
                          id: led_strip
                          relative_brightness: -2%
                          transition_length: 200ms
                      - delay: 100ms

      # Double Press
      - timing:
          - ON for at most 400ms
          - OFF for at most 500ms
          - ON for at most 500ms
          - OFF for at least 200ms
        then:
          - light.turn_on:
              id: led_strip
              brightness: !lambda "return id(saved_brightness);"

      # Single Press
      - timing:
          - ON for at most 500ms
          - OFF for at least 200ms
        then:
          - light.toggle: led_strip
